### ISSUE TITLE
No errors when no inequality is added

### ISSUE THREAD

**Issue by rafaelamaribeiro** [andrewrosemberg/OptimalBids.jl#3]
On the example with `Nonconvex.jl`, there is a comment saying that it doesn't work when no inequalities are added. https://github.com/andrewrosemberg/OptimalBids.jl/blob/24c57bd9204bc08e1a7143dd22a90bd663f111a8/docs/src/examples/Nonconvex.md?plain=1#L103

When I run the code as-is, I find that the maximum Profit is `78849.85061111911`, with the Multiplicative Factor of `27.239617121582047`, as can be seen on the following image:

![with inequality](https://user-images.githubusercontent.com/62032270/155314976-feddd8b0-063f-41ea-b509-32817476e9d6.png)

However, if I run without the inequality, not only the code works but I find a higher maximum Profit, at the value of `80897.18985312385`, with the Multiplicative Factor of `30.44499859189181`, as can be seen on the following image:

![no inequalities](https://user-images.githubusercontent.com/62032270/155316411-1f4dcd7f-64e0-456a-8c06-14257fb3b186.png)

In the next image, it is possible to see both solutions on the same graphic, where the higher value represents the case without the inequality.

![both with and without inequality](https://user-images.githubusercontent.com/62032270/155316659-c7978249-fb8e-4400-b07f-475a7c47c7d9.png)

**Comment by andrewrosemberg** [comment]
Interesting, could you send me a print of your environment @rafaelamaribeiro ? `] st`

**Comment by rafaelamaribeiro** [comment]
![env part 1](https://user-images.githubusercontent.com/62032270/155362626-76dc9f90-0f37-4fc2-a265-d6808976035a.png)
![env part 2](https://user-images.githubusercontent.com/62032270/155362638-cdef4167-c6e9-43af-81cc-d0264fdc5dd0.png)

**Comment by andrewrosemberg** [comment]
The script should not work with this environment since `JuMP = "^0.22"` in compat.
Maybe try using a new environment to avoid differences in packages versions.
